# Generated by Django 6.0.6 on 2026-07-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_rua',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
