# Generated by Django 6.0.6 on 2026-07-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoproduto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='variacoes/'),
        ),
    ]
