# Generated by Django 6.0.6 on 2026-07-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
